version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/clean-todo
permissions:
  - object: /home/ec2-user/clean-todo
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /home/ec2-user/clean-todo
    owner: ec2-user
    group: ec2-user
    mode: 644
    type:
      - file
hooks:
  ApplicationStop:
    - location: deployment/scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: deployment/scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deployment/scripts/after_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: deployment/scripts/application_start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deployment/scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
