version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    container_name: laravel-db
    command: >
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/mysql-slow.log
      --long_query_time=0.1
      --log_queries_not_using_indexes=1
      --general_log=1
      --general_log_file=/var/log/mysql/mysql-query.log
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./storage/mysql-logs:/var/log/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db-data:
